### ISSUE TITLE
NodePort is a missing parameter

### ISSUE THREAD

**Issue by lovesuper** [rowanruseler/pgadmin#1]
Please, add service.nodePort to supported parameters. Thanks!
Something like this:

```
      {{- if .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
```

**Comment by rowanruseler** [comment]
@lovesuper thank you for creating an issue.

Do you mean the container port? The one that is currently port 80?

**Comment by lovesuper** [comment]
Service.nodePort for accessing through NodePort mode.

**Comment by rowanruseler** [comment]
@lovesuper you mean https://github.com/rowanruseler/pgadmin4/blob/411dd030202bfe6281f2ee0a56d98397fc1cbc1b/values.yaml#L14 

Or am I missing something here?

**Comment by lovesuper** [comment]
https://github.com/helm/charts/blob/592a37676f737ebdfa00cda516550571576febea/stable/postgresql/templates/svc.yaml#L33

**Comment by rowanruseler** [comment]
@lovesuper ah cool, will create a PR today.

Btw, this repo is moved: https://github.com/rowanruseler/helm-charts

I'll make sure it will be added there. Sorry you got just in between a repo migration :)
